# Generated by Django 3.2 on 2021-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupWeekTypeChoice',
            field=models.CharField(choices=[('1', 'Нечетная'), ('2', 'Четная'), ('-1', 'Не учитывать')], default=None, max_length=2, verbose_name='Тип первой учебной недели'),
        ),
    ]
